
language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.11

before_install:
  - export DJANGO_SETTINGS_MODULE=django-accountkit.settings

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
